### ISSUE TITLE
Installing using setup.py fails

### ISSUE THREAD

**Issue by gustavo-grieco** [agroce/echidna-parade#4]
Installing using `python3 setup.py install --user` instead of pip3 produces the following error:

```
Traceback (most recent call last):
  File "/home/g/.local/bin/echidna-parade", line 33, in <module>
    sys.exit(load_entry_point('echidna-parade==0.1', 'console_scripts', 'echidna-parade')())
  File "/home/g/.local/bin/echidna-parade", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/g/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'echidna_parade'
```

**Comment by agroce** [comment]
Hmm.  Works for me?

```
running install
running bdist_egg
running egg_info
writing echidna_parade.egg-info/PKG-INFO
writing dependency_links to echidna_parade.egg-info/dependency_links.txt
writing entry points to echidna_parade.egg-info/entry_points.txt
writing requirements to echidna_parade.egg-info/requires.txt
writing top-level names to echidna_parade.egg-info/top_level.txt
package init file 'echidna_parade/__init__.py' not found (or not a regular file)
reading manifest file 'echidna_parade.egg-info/SOURCES.txt'
writing manifest file 'echidna_parade.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/echidna_parade
copying echidna_parade/echidna_parade.py -> build/lib/echidna_parade
creating build/bdist.macosx-10.9-x86_64
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/echidna_parade
copying build/lib/echidna_parade/echidna_parade.py -> build/bdist.macosx-10.9-x86_64/egg/echidna_parade
byte-compiling build/bdist.macosx-10.9-x86_64/egg/echidna_parade/echidna_parade.py to echidna_parade.cpython-37.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying echidna_parade.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying echidna_parade.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying echidna_parade.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying echidna_parade.egg-info/entry_points.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying echidna_parade.egg-info/requires.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying echidna_parade.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/echidna_parade-0.1-py3.7.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing echidna_parade-0.1-py3.7.egg
Copying echidna_parade-0.1-py3.7.egg to /Users/adg326/.local/lib/python3.7/site-packages
Adding echidna-parade 0.1 to easy-install.pth file
Installing echidna-parade script to /Users/adg326/.local/bin

Installed /Users/adg326/.local/lib/python3.7/site-packages/echidna_parade-0.1-py3.7.egg
Processing dependencies for echidna-parade==0.1
Searching for crytic-compile==0.1.12
Best match: crytic-compile 0.1.12
Adding crytic-compile 0.1.12 to easy-install.pth file
Installing crytic-compile script to /Users/adg326/.local/bin

Using /Users/adg326/opt/anaconda3/lib/python3.7/site-packages
Searching for slither-analyzer==0.7.0
Best match: slither-analyzer 0.7.0
Adding slither-analyzer 0.7.0 to easy-install.pth file
Installing slither script to /Users/adg326/.local/bin
Installing slither-check-erc script to /Users/adg326/.local/bin
Installing slither-check-kspec script to /Users/adg326/.local/bin
Installing slither-check-upgradeability script to /Users/adg326/.local/bin
Installing slither-find-paths script to /Users/adg326/.local/bin
Installing slither-flat script to /Users/adg326/.local/bin
Installing slither-format script to /Users/adg326/.local/bin
Installing slither-mutate script to /Users/adg326/.local/bin
Installing slither-prop script to /Users/adg326/.local/bin
Installing slither-simil script to /Users/adg326/.local/bin

Using /Users/adg326/opt/anaconda3/lib/python3.7/site-packages
Searching for PyYAML==5.1.2
Best match: PyYAML 5.1.2
Adding PyYAML 5.1.2 to easy-install.pth file

Using /Users/adg326/opt/anaconda3/lib/python3.7/site-packages
Searching for pysha3==1.0.2
Best match: pysha3 1.0.2
Adding pysha3 1.0.2 to easy-install.pth file

Using /Users/adg326/opt/anaconda3/lib/python3.7/site-packages
Searching for prettytable==0.7.2
Best match: prettytable 0.7.2
Adding prettytable 0.7.2 to easy-install.pth file

Using /Users/adg326/opt/anaconda3/lib/python3.7/site-packages
Finished processing dependencies for echidna-parade==0.1
(base) cmp3149:echidna-parade adg326$ 
```

**Comment by agroce** [comment]
If you don't see this again, I'm closing, since it's worked on mac and linux for me.
